In [2]:
import numpy as np

In [34]:
import cv2

# Load the cascade
face_cascade = cv2.CascadeClassifier(r'C:\Users\gtanwar2\Desktop\haarcascade_frontalface_default.xml')
nose_cascade = cv2.CascadeClassifier(r'C:\Users\gtanwar2\Documents\Mask Detection Project\haarcascade_mcs_nose.xml')

In [38]:
def detect_faces(image):
    # Read the input image
    img = cv2.imread(os.path.join(r'C:\Users\gtanwar2\Documents\Mask Detection Project\Orginal Images',image))

    # Convert into grayscale
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    noses = detect_noses(gray)
    # Detect faces
    faces = face_cascade.detectMultiScale(gray,1.02, 10,minSize = (80, 80))

    # print(faces)
    # Draw rectangle around the faces
    for (x, y, w, h) in faces:
        cv2.rectangle(img, (x, y), (x + w, y + h), (0,255, 0), 2)
    for (x, y, w, h) in noses:
        cv2.rectangle(img, (x, y), (x + w, y + h), (0,0, 255), 2)
    # cv2.rectangle(img, (40, 40), (80+40, 80+40), (255, 0, 0), 2)
    # Display the output
    cv2.imwrite(os.path.join(r'C:\Users\gtanwar2\Documents\Mask Detection Project\detected faces',image),img)

In [39]:
def detect_noses(gray):

    # Detect faces
    noses = nose_cascade.detectMultiScale(gray,1.02, 10)

    return noses
    # # print(faces)
    # # Draw rectangle around the faces
    # for (x, y, w, h) in noses:
    #     cv2.rectangle(img, (x, y), (x + w, y + h), (0,255, 0), 2)
    # # cv2.rectangle(img, (40, 40), (80+40, 80+40), (255, 0, 0), 2)
    # # Display the output
    # cv2.imwrite(os.path.join(r'C:\Users\gtanwar2\Documents\Mask Detection Project\detected faces',image),img)


In [41]:
# import os

# path = r'C:\Users\gtanwar2\Documents\Mask Detection Project\Orginal Images'

# for file in os.listdir(path):
#     print(file)
#     detect_noses(file)

In [12]:
import os
root = r'C:\Users\gtanwar2\Documents\Mask Detection Project\Orginal Images'
path = r'C:\Users\gtanwar2\Documents\Mask Detection Project\Orginal Images'
img_paths = []
for file in os.listdir(path):
    img_paths.append(os.path.join(root,file))
    # detect_faces(file)
    


In [13]:
img_paths

['C:\\Users\\gtanwar2\\Documents\\Mask Detection Project\\Orginal Images\\1.jpg',
 'C:\\Users\\gtanwar2\\Documents\\Mask Detection Project\\Orginal Images\\3.jpg',
 'C:\\Users\\gtanwar2\\Documents\\Mask Detection Project\\Orginal Images\\4.jpg',
 'C:\\Users\\gtanwar2\\Documents\\Mask Detection Project\\Orginal Images\\5.jpg',
 'C:\\Users\\gtanwar2\\Documents\\Mask Detection Project\\Orginal Images\\harshad.jpg',
 'C:\\Users\\gtanwar2\\Documents\\Mask Detection Project\\Orginal Images\\mall.jpg',
 'C:\\Users\\gtanwar2\\Documents\\Mask Detection Project\\Orginal Images\\nirav1.jpg',
 'C:\\Users\\gtanwar2\\Documents\\Mask Detection Project\\Orginal Images\\nirav2.jpg',
 'C:\\Users\\gtanwar2\\Documents\\Mask Detection Project\\Orginal Images\\Scam_1992_Harshad_Mehta_Story.jpg']

In [21]:
detect_faces(r'C:\Users\gtanwar2\Documents\Mask Detection Project\Orginal Images\2.jpg')

[[744 694  87  87]
 [165 491  86  86]
 [642 440 117 117]
 [233 789  95  95]
 [562 698 105 105]
 [765 746 113 113]
 [288 412 121 121]
 [243 819 147 147]]


In [64]:
## detect face if there is an eye found within than bouding box
## look for more rules


In [6]:
import cv2 as cv

print(cv.__version__)
RED = (0, 0, 255)
scaleFactor = 1.1
minNeighbors = 5
minSize = (30, 30)

def detect():
    rects = face_detector.detectMultiScale(gray, 
        scaleFactor=scaleFactor,
        minNeighbors=minNeighbors, 
        minSize=minSize, 
        flags=cv.CASCADE_SCALE_IMAGE)

    print(f'found {len(rects)} face(s)')

    img = img0.copy()
    for rect in rects:
        cv.rectangle(img, rect, RED, 2)
    cv.imshow('window', img)

def trackbar(x):
    global minSize, minNeighbors, scaleFactor
    i = cv.getTrackbarPos('size','window')
    d = (24, 30, 60, 120)[i]
    minSize = (d, d)
    
    n = cv.getTrackbarPos('neighbors','window') + 1
    minNeighbors = n

    i = cv.getTrackbarPos('scale','window')
    s = (1.05, 1.1, 1.4, 2)[i]
    scaleFactor
    
    text = f'minNeighbors={n}, minSize={d}, scaleFactor={s}'
    # cv.displayOverlay()
    cv.displayOverlay('window', text)
    detect()

img0 = cv.imread(r'C:\Users\gtanwar2\Documents\Mask Detection Project\Orginal Images\2.jpg')
img = img0.copy()
gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)

path = r'C:\Users\gtanwar2\Desktop\haarcascade_frontalface_default.xml'
face_detector = cv.CascadeClassifier(path)

detect()

cv.createTrackbar('neighbors', 'window', 0, 10, trackbar)
cv.createTrackbar('size', 'window', 0, 3, trackbar)
cv.createTrackbar('scale', 'window', 0, 3, trackbar)
cv.waitKey(0)

4.5.4-dev
found 5 face(s)


error: OpenCV(4.5.4-dev) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:1202: error: (-213:The function/feature is not implemented) The library is compiled without QT support in function 'cv::displayOverlay'


-1

In [1]:
import dlib
import cv2
 
#We create the model here with the weights placed as parameters
face_detect = dlib.cnn_face_detection_model_v1(r"C:\Users\gtanwar2\Downloads\mmod_human_face_detector.dat\mmod_human_face_detector.dat")


 
# while True:
#    ret, frame = cap.read()
#    frame = cv2.resize(frame, (600, 400))
 
#    faces = face_detect(frame, 1)
#    for face in faces:
#        # In dlib in order to extract points we need to do this
#        x1 = face.rect.left()
#        y1 = face.rect.bottom()
#        x2 = face.rect.right()
#        y2 = face.rect.top()
#        cv2.rectangle(frame, (x1, y1), (x2, y2), (255, 0, 0), 1)
 
#    cv2.imshow("Frame", frame)
#    if cv2.waitKey(25) & 0xFF == ord('q'):
#        break
 
# cap.release()
# cv2.destroyAllWindows()

In [2]:
image = cv2.imread(os.path.join(r'C:\Users\gtanwar2\Documents\Mask Detection Project\Orginal Images\harshad.jpg'))
faces_cnn = face_detect(image,1)
for face in faces_cnn:
    x = face.rect.left()
    y = face.rect.top()
    w = face.rect.right() - x
    h = face.rect.bottom() - y

     # draw box over face
    cv2.rectangle(image, (x,y), (x+w,y+h), (0,0,255), 2)
cv2.imshow("Frame", image)

In [ ]:
for face in faces_cnn:
    x = face.rect.left()
    y = face.rect.top()
    w = face.rect.right() - x
    h = face.rect.bottom() - y

     # draw box over face
    cv2.rectangle(image, (x,y), (x+w,y+h), (0,0,255), 2)
cv2.imwrite(os.path.join(r'C:\Users\gtanwar2\Documents\Mask Detection Project\detected faces','new.jpg'),image)

In [2]:
import dlib
import cv2
 
#We create the model here with the weights placed as parameters
face_detect = dlib.cnn_face_detection_model_v1("/content/mmod_human_face_detector.dat")

cap = cv2.VideoCapture("data.mp4")
 
while True:
   ret, frame = cap.read()
   frame = cv2.resize(frame, (600, 400))
 
   faces = face_detect(frame, 1)
   for face in faces:
       # In dlib in order to extract points we need to do this
       x1 = face.rect.left()
       y1 = face.rect.bottom()
       x2 = face.rect.right()
       y2 = face.rect.top()
       cv2.rectangle(frame, (x1, y1), (x2, y2), (255, 0, 0), 1)
 
   cv2.imshow("Frame", frame)
   if cv2.waitKey(25) & 0xFF == ord('q'):
       break
 
cap.release()
cv2.destroyAllWindows()

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 22)

In [2]:
import numpy as np
import cv2
cap = cv2.VideoCapture(0)
cap.set(3,640) # set Width
cap.set(4,480) # set Height
while(True):
    ret, frame = cap.read()
    # frame = cv2.flip(frame, -1) # Flip camera vertically
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    
    cv2.imshow('frame', frame)
    cv2.imshow('gray', gray)
    
    k = cv2.waitKey(30) & 0xff
    if k == 27: # press 'ESC' to quit
        break
cap.release()
cv2.destroyAllWindows()

In [14]:
from imutils import paths
import face_recognition
import pickle
import cv2
import os
 
#get paths of each file in folder named Images
#Images here contains my data(folders of various persons)
imagePaths = img_paths
knownEncodings = []
knownNames = []
# loop over the image paths
for (i, imagePath) in enumerate(imagePaths):
    # extract the person name from the image path
    name = imagePath.split(os.path.sep)[-2]
    # load the input image and convert it from BGR (OpenCV ordering)
    # to dlib ordering (RGB)
    image = cv2.imread(imagePath)
    rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    #Use Face_recognition to locate faces
    boxes = face_recognition.face_locations(rgb,model='hog')
    # compute the facial embedding for the face
    encodings = face_recognition.face_encodings(rgb, boxes)
    # loop over the encodings
    for encoding in encodings:
        knownEncodings.append(encoding)
        knownNames.append(name)
#save emcodings along with their names in dictionary data
data = {"encodings": knownEncodings, "names": knownNames}
#use pickle to save data into a file for later use
f = open("face_enc", "wb")
f.write(pickle.dumps(data))
f.close()

In [11]:
paths

<module 'imutils.paths' from 'C:\\Users\\gtanwar2\\Anaconda3\\lib\\site-packages\\imutils\\paths.py'>

In [18]:
import face_recognition
import imutils
import pickle
import time
import cv2
import os
 
#find path of xml file containing haarcascade file
cascPathface = r'C:\Users\gtanwar2\Downloads\haarcascade_frontalface_alt2.xml'
# load the harcaascade in the cascade classifier
faceCascade = cv2.CascadeClassifier(cascPathface)
# load the known faces and embeddings saved in last file
data = pickle.loads(open('face_enc', "rb").read())
#Find path to the image you want to detect face and pass it here
image = cv2.imread(r'C:\Users\gtanwar2\Desktop\download.jpg')
rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
#convert image to Greyscale for haarcascade
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
faces = faceCascade.detectMultiScale(gray,
                                     scaleFactor=1.1,
                                     minNeighbors=5,
                                     minSize=(60, 60),
                                     flags=cv2.CASCADE_SCALE_IMAGE)
 
# the facial embeddings for face in input
encodings = face_recognition.face_encodings(rgb)
names = []
# loop over the facial embeddings incase
# we have multiple embeddings for multiple fcaes
for encoding in encodings:
    #Compare encodings with encodings in data["encodings"]
    #Matches contain array with boolean values and True for the embeddings it matches closely
    #and False for rest
    matches = face_recognition.compare_faces(data["encodings"],
    encoding)
    #set name =inknown if no encoding matches
    name = "Unknown"
    # check to see if we have found a match
    if True in matches:
        #Find positions at which we get True and store them
        matchedIdxs = [i for (i, b) in enumerate(matches) if b]
        counts = {}
        # loop over the matched indexes and maintain a count for
        # each recognized face face
        for i in matchedIdxs:
            #Check the names at respective indexes we stored in matchedIdxs
            name = data["names"][i]
            #increase count for the name we got
            counts[name] = counts.get(name, 0) + 1
            #set name which has highest count
            name = max(counts, key=counts.get)
 
 
        # update the list of names
        names.append(name)
        # loop over the recognized faces
        for ((x, y, w, h), name) in zip(faces, names):
            # rescale the face coordinates
            # draw the predicted face name on the image
            cv2.rectangle(image, (x, y), (x + w, y + h), (0, 255, 0), 2)
            cv2.putText(image, name, (x, y), cv2.FONT_HERSHEY_SIMPLEX,
             0.75, (0, 255, 0), 2)
    cv2.imshow("Frame", image)
    cv2.waitKey(0)

In [1]:
import face_recognition
import os
import cv2


KNOWN_FACES_DIR = r'C:\Users\gtanwar2\Documents\Mask Detection Project\Known Faces'
UNKNOWN_FACES_DIR = r'C:\Users\gtanwar2\Documents\Mask Detection Project\Unknown Faces'
TOLERANCE = 0.6
FRAME_THICKNESS = 3
FONT_THICKNESS = 2
MODEL = 'cnn'  # 'hog' or 'cnn' - CUDA accelerated (if available) deep-learning pretrained model

In [2]:
print('Loading known faces...')
known_faces = []
known_names = []

Loading known faces...


In [3]:
for name in os.listdir(KNOWN_FACES_DIR):

    # Next we load every file of faces of known person
    for filename in os.listdir(f'{KNOWN_FACES_DIR}/{name}'):

        # Load an image
        image = face_recognition.load_image_file(f'{KNOWN_FACES_DIR}/{name}/{filename}')

        # Get 128-dimension face encoding
        # Always returns a list of found faces, for this purpose we take first face only (assuming one face per image as you can't be twice on one image)
        encoding = face_recognition.face_encodings(image)[0]

        # Append encodings and name
        known_faces.append(encoding)
        known_names.append(name)

In [4]:
known_faces

[array([-7.02327415e-02,  1.70724079e-01,  7.52234012e-02, -8.66325945e-02,
        -7.20288679e-02,  8.27061012e-05, -6.41199350e-02, -1.08006708e-01,
         1.68033734e-01, -8.11456963e-02,  2.86977232e-01,  1.59884077e-02,
        -2.51314104e-01, -1.93874165e-01, -9.72905308e-02,  9.97186452e-02,
        -1.49272025e-01, -1.17705800e-01, -7.98461437e-02, -2.95985341e-02,
        -4.44962010e-02,  1.07528223e-02,  8.62312391e-02, -4.32314500e-02,
        -5.71180508e-02, -4.20511872e-01, -1.10826500e-01, -5.85178807e-02,
         8.74773115e-02, -6.12615049e-02, -3.66940536e-02,  1.87640917e-02,
        -1.92697033e-01, -1.11513846e-01,  1.19760893e-02,  6.73351288e-02,
         2.14098059e-02,  3.57021242e-02,  1.63588554e-01,  6.05177395e-02,
        -1.09327011e-01, -2.12541111e-02,  4.44337502e-02,  2.96607912e-01,
         1.84787437e-01,  1.07843742e-01,  4.00777161e-02, -6.52262866e-02,
         6.50295690e-02, -2.23433584e-01,  1.49872676e-01,  1.28824130e-01,
         1.8

In [6]:
import numpy as np
a_file = open("test.txt", "w")
for row in known_faces:
    np.savetxt(a_file, row)
a_file.close()


In [5]:
known_faces

[array([-7.02327415e-02,  1.70724079e-01,  7.52234012e-02, -8.66325945e-02,
        -7.20288679e-02,  8.27061012e-05, -6.41199350e-02, -1.08006708e-01,
         1.68033734e-01, -8.11456963e-02,  2.86977232e-01,  1.59884077e-02,
        -2.51314104e-01, -1.93874165e-01, -9.72905308e-02,  9.97186452e-02,
        -1.49272025e-01, -1.17705800e-01, -7.98461437e-02, -2.95985341e-02,
        -4.44962010e-02,  1.07528223e-02,  8.62312391e-02, -4.32314500e-02,
        -5.71180508e-02, -4.20511872e-01, -1.10826500e-01, -5.85178807e-02,
         8.74773115e-02, -6.12615049e-02, -3.66940536e-02,  1.87640917e-02,
        -1.92697033e-01, -1.11513846e-01,  1.19760893e-02,  6.73351288e-02,
         2.14098059e-02,  3.57021242e-02,  1.63588554e-01,  6.05177395e-02,
        -1.09327011e-01, -2.12541111e-02,  4.44337502e-02,  2.96607912e-01,
         1.84787437e-01,  1.07843742e-01,  4.00777161e-02, -6.52262866e-02,
         6.50295690e-02, -2.23433584e-01,  1.49872676e-01,  1.28824130e-01,
         1.8

In [10]:
original_array = np.loadtxt("test.txt").reshape(4, 128)

In [7]:
import numpy as np
np.save('a.npy', known_faces, allow_pickle=True)
b = np.load('a.npy', allow_pickle=True)

In [8]:
b

array([[-7.02327415e-02,  1.70724079e-01,  7.52234012e-02,
        -8.66325945e-02, -7.20288679e-02,  8.27061012e-05,
        -6.41199350e-02, -1.08006708e-01,  1.68033734e-01,
        -8.11456963e-02,  2.86977232e-01,  1.59884077e-02,
        -2.51314104e-01, -1.93874165e-01, -9.72905308e-02,
         9.97186452e-02, -1.49272025e-01, -1.17705800e-01,
        -7.98461437e-02, -2.95985341e-02, -4.44962010e-02,
         1.07528223e-02,  8.62312391e-02, -4.32314500e-02,
        -5.71180508e-02, -4.20511872e-01, -1.10826500e-01,
        -5.85178807e-02,  8.74773115e-02, -6.12615049e-02,
        -3.66940536e-02,  1.87640917e-02, -1.92697033e-01,
        -1.11513846e-01,  1.19760893e-02,  6.73351288e-02,
         2.14098059e-02,  3.57021242e-02,  1.63588554e-01,
         6.05177395e-02, -1.09327011e-01, -2.12541111e-02,
         4.44337502e-02,  2.96607912e-01,  1.84787437e-01,
         1.07843742e-01,  4.00777161e-02, -6.52262866e-02,
         6.50295690e-02, -2.23433584e-01,  1.49872676e-0

In [9]:
print('Processing unknown faces...')
# Now let's loop over a folder of faces we want to label
for filename in os.listdir(UNKNOWN_FACES_DIR):

    # Load image
    print(f'Filename {filename}', end='')
    image = face_recognition.load_image_file(f'{UNKNOWN_FACES_DIR}/{filename}')

    # This time we first grab face locations - we'll need them to draw boxes
    locations = face_recognition.face_locations(image, model=MODEL)

    # Now since we know loctions, we can pass them to face_encodings as second argument
    # Without that it will search for faces once again slowing down whole process
    encodings = face_recognition.face_encodings(image, locations)

    # We passed our image through face_locations and face_encodings, so we can modify it
    # First we need to convert it from RGB to BGR as we are going to work with cv2
    image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
    
    print(f', found {len(encodings)} face(s)')
    for face_encoding, face_location in zip(encodings, locations):

        # We use compare_faces (but might use face_distance as well)
        # Returns array of True/False values in order of passed known_faces
        results = face_recognition.compare_faces(b, face_encoding, TOLERANCE)
        print(results)
        match = None
        if True in results:
            match = known_names[results.index(True)]
            top_left = (face_location[3],face_location[0])
            bottom_right = (face_location[1],face_location[2])
            
            color = [0,255,0]
            # Paint frame
            cv2.rectangle(image, top_left, bottom_right, color, FRAME_THICKNESS)

            # Now we need smaller, filled grame below for a name
            # This time we use bottom in both corners - to start from bottom and move 50 pixels down
            top_left = (face_location[3], face_location[2])
            bottom_right = (face_location[1], face_location[2] + 22)

            # Paint frame
            cv2.rectangle(image, top_left, bottom_right, color, cv2.FILLED)

            # Wite a name
            cv2.putText(image, match, (face_location[3] + 10, face_location[2] + 15), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (200, 200, 200), FONT_THICKNESS)
    # Show image
    cv2.imshow(filename, image)
    cv2.waitKey(0)
    cv2.destroyWindow(filename)
    


Processing unknown faces...
Filename d.jpg, found 1 face(s)
[False, False, True, True]
Filename download (1).jpg, found 1 face(s)
[True, False, False, False]
Filename download (2).jpg, found 1 face(s)
[False, False, False, False]
Filename download (3).jpg, found 1 face(s)
[False, True, False, False]
Filename download.jpg, found 1 face(s)
[False, False, False, False]
Filename images (1).jpg, found 0 face(s)
Filename images (2).jpg, found 1 face(s)
[True, True, False, False]
Filename images (3).jpg, found 1 face(s)
[True, True, False, False]
Filename images (4).jpg, found 1 face(s)
[False, False, False, False]
Filename images (5).jpg, found 1 face(s)
[False, False, False, True]
Filename images.jpg, found 1 face(s)
[True, False, False, False]
Filename sachin_sehwag.jpg, found 2 face(s)
[True, True, False, False]
[False, False, True, True]
